name: stock-backtesting-engine-streamlit-ui
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - altair==6.0.0
      - anyio==4.12.0
      - attrs==25.4.0
      - backports-tarfile==1.2.0
      - blinker==1.9.0
      - build==1.3.0
      - cachecontrol==0.14.4
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cleo==2.1.0
      - click==8.3.1
      - crashtest==0.4.1
      - distlib==0.4.0
      - dulwich==0.24.10
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - findpython==0.7.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - importlib-metadata==8.7.0
      - installer==0.7.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keyring==25.7.0
      - markupsafe==3.0.3
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - narwhals==2.13.0
      - numpy==2.3.5
      - packaging==25.0
      - pandas==2.3.3
      - pbs-installer==2025.12.2
      - pillow==12.0.0
      - pkginfo==1.12.1.2
      - platformdirs==4.5.0
      - plotly==6.5.0
      - poetry==2.2.1
      - poetry-core==2.2.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydeck==0.9.1
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rapidfuzz==3.14.3
      - referencing==0.37.0
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rpds-py==0.30.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.52.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tomlkit==0.13.3
      - tornado==6.5.2
      - trove-classifiers==2025.12.1.14
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - virtualenv==20.35.4
      - xattr==1.3.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/stock-backtesting-engine-streamlit-ui
