name: stock-backtesting-engine-streamlit-ui
channels:
  - conda-forge

dependencies:
  - python=3.11.14
  - numpy
  - pandas
  - requests
  - pip

  - pip:
      - streamlit
      - plotly
      - yfinance
